nginx:
  build: ./nginx/
  links:
    - php
  volumes_from:
    - app

php:
  build: ./php/
  expose:
    - "9000"
  links:
    - mysql
  volumes_from:
    - app

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes_from:
    - data

app:
  image: php:7.0-fpm

data:
  image: mysql:latest
  command: "true"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - mysql
  environment:
    PMA_HOST: mysql