nginx:
  ports:
    - "3000:80"

app:
  volumes:
    - ./src:/var/www/html/src

data:
  volumes:
    - /var/lib/mysql

mysql:
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: auth
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

